// React/src/App.js
import React, { useState, useCallback } from 'react';

import 'devextreme/dist/css/dx.common.css';
import 'devextreme/dist/css/dx.light.css';
import './App.css';

import TabPanel, { Item } from "devextreme-react/tab-panel";
import Form, { SimpleItem } from "devextreme-react/form";
import TextArea from "devextreme-react/text-area";
import RadioGroup from "devextreme-react/radio-group";

const employeeData = {
  name: 'John Heart',
  position: 'CEO',
  hireDate: new Date(2012, 4, 13),
  officeNumber: 901,
  notes: 'John has been in the Audio/Video industry since 1990. He has led DevAV as its CEO since 2003.',
  roles: ['Chief Officer', 'Administrator', 'Manager']
};

const tabNames = ['Employee', 'Notes', 'Role'];

function App() {
  const [selectedTabIndex, setSelectedTabIndex] = useState(0);
 
  const onRadioGroupValueChanged = useCallback((e) => {
    setSelectedTabIndex(tabNames.indexOf(e.value));
  }, []);

  const onTabSelectionChanged = useCallback((e) => {
    setSelectedTabIndex(tabNames.indexOf(e.addedItems[0].title));
  }, []);

  return (
    <div>
      <TabPanel 
        id="tabPanel"
        loop={true}
        animationEnabled={true} 
        swipeEnabled={true}
        selectedIndex={selectedTabIndex}
        onSelectionChanged={onTabSelectionChanged}>
          <Item title="Employee" icon="floppy">
            <Form formData={employeeData}>
              <SimpleItem dataField="name" />
              <SimpleItem dataField="position" />
              <SimpleItem dataField="hireDate" />
              <SimpleItem dataField="officeNumber" />
            </Form>
          </Item>
          <Item title="Notes" icon="comment">
            <TextArea 
              id="textArea"
              defaultValue={employeeData.notes}
            />
          </Item>
          <Item title="Role" icon="isnotblank" badge="new">
            <RadioGroup 
              items={employeeData.roles}
              defaultValue={employeeData.roles[0]}
            />
          </Item>
      </TabPanel>

      <RadioGroup 
        items={tabNames}
        value={tabNames[selectedTabIndex]}
        layout="horizontal"
        onValueChanged={onRadioGroupValueChanged}
      />
    </div>
  )
}

export default App;

// Angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  employeeData = {
    name: 'John Heart',
    position: 'CEO',
    hireDate: new Date(2012, 4, 13),
    officeNumber: 901,
    notes: 'John has been in the Audio/Video industry since 1990. He has led DevAV as its CEO since 2003.',
    roles: ['Chief Officer', 'Administrator', 'Manager']
  }

  tabNames = ['Employee', 'Notes', 'Role']

  selectedTabIndex = 0;

  onValueChanged(e){
    this.selectedTabIndex = this.tabNames.indexOf(e.value);
  }
}

<div id="app-container">
  <dx-tab-panel 
    id="tabPanel"
    [loop]="true"
    [animationEnabled]="true"
    [swipeEnabled]="true"
    [(selectedIndex)]="selectedTabIndex">    
    <dxi-item title="Employee" icon="floppy">
        <div *dxTemplate>
            <dx-form
                [formData]="employeeData">
                <dxi-item dataField="name"></dxi-item>
                <dxi-item dataField="position"></dxi-item>
                <dxi-item dataField="hireDate"></dxi-item>
                <dxi-item dataField="officeNumber"></dxi-item>      
            </dx-form>
        </div>
    </dxi-item>
    <dxi-item title="Notes" icon="comment">
      <div *dxTemplate>
          <dx-text-area
              id="textArea"
              [(value)]="employeeData.notes">
          </dx-text-area>
      </div>
    </dxi-item>
    <dxi-item title="Role" icon="isnotblank" badge="new">
      <div *dxTemplate>
          <dx-radio-group
              [items]="employeeData.roles"
              [(value)]="employeeData.roles[0]">
          </dx-radio-group>
      </div>
    </dxi-item>
  </dx-tab-panel>

  <dx-radio-group
        [items]="tabNames"
        [value]="tabNames[selectedTabIndex]"
        layout="horizontal"
        (onValueChanged)="onValueChanged($event)">
    </dx-radio-group>
</div>
